workflows:
  build-apk:
    name: Build APK Release
    max_build_duration: 30
    environment:
      flutter: stable
    scripts:
      - name: Build APK
        script: |
          flutter clean
          flutter pub get
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - boyzestsumbayak@gmail.com
